name: Release Binary

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - run: brew install opencv
      - run: go build -o frostyfriend-darwin-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: frostyfriend-darwin-arm64
          path: frostyfriend-darwin-arm64

  build-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - run: brew install opencv
      - run: go build -o frostyfriend-darwin-amd64
      - uses: actions/upload-artifact@v4
        with:
          name: frostyfriend-darwin-amd64
          path: frostyfriend-darwin-amd64

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-arm64, build-amd64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            frostyfriend-darwin-arm64
            frostyfriend-darwin-amd64