name: Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Dependencies ARM64
        run: |
          arch -arm64 brew install opencv

      - name: Install Dependencies AMD64
        run: |
          arch -x86_64 brew install opencv

      - name: Build ARM64
        run: |
          arch -arm64 go build -o frostyfriend-darwin-arm64
          
      - name: Build AMD64
        run: |
          arch -x86_64 go build -o frostyfriend-darwin-amd64
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            frostyfriend-darwin-arm64
            frostyfriend-darwin-amd64